[config]
# TODO: Should the user provide the absolute path from the root directory to the schema file (i.e. it should start with a forward slash) or the relative file path?
schemas_dir = "./schemas"
schema = "schema.v1.gqlr"
validate_schema_in_envs = ["development"]
validate_query_in_envs = ["development", "test", "staging"] # Define the environments where queries should be validated against the schema. Queries are set during development and don't change after that. So if the queries are validated during development, then I don't think they need to be validated in production. This will make the queries faster in production because the query validation step can be skipped.
format_query_results_hierarchically = true # Users can set the default formatting for query results by setting `formatQueryResultsHierarchically` to `true` or `false`. Users can also set the formatting for their queries on a case by case basis by passing `true` or `false` as the third parameter to the quigley function.

[connection]
username = "myUsername"
password = "myPassword"
host = "localhost"
port = 6379
graph = "myGraph"
